/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/scene.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const { nodes, materials } = useGLTF('models/scene.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.CR_videogamecoins} position={[-12.343, 2.261, 4.114]} rotation={[-Math.PI / 2, 0, 0]} />
      <group position={[-15.817, 1.774, 3.163]} rotation={[-Math.PI / 2, 0, -1.635]} scale={3.185}>
        <mesh geometry={nodes.Object_2001.geometry} material={materials['CR_videogame_door.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['CR_videogame_machine.001']} />
        <mesh geometry={nodes.Object_4001.geometry} material={materials['CR_videogamecoins.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['CR_videogamedesign2.001']} />
      </group>
      <group position={[-0.084, 1.756, 0.191]} scale={15.755}>
        <mesh geometry={nodes.pPlane9_SEVEN_0.geometry} material={materials.SEVEN} scale={[1.312, 1, 1.252]} />
      </group>
      <mesh geometry={nodes.polySurface100_FIVE_0.geometry} material={materials.FIVE} position={[-4.27, 1.756, 2.59]} />
      <mesh geometry={nodes.polySurface103_FIVE_0.geometry} material={materials.FIVE} position={[-4.087, 1.756, 2.416]} />
      <mesh geometry={nodes.polySurface107_FIVE_0.geometry} material={materials.FIVE} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface109_FIVE_0.geometry} material={materials.FIVE} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface114_FIVE_0.geometry} material={materials.FIVE} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface117_FIVE_0.geometry} material={materials.FIVE} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface123_FIVE_0.geometry} material={materials.FIVE} position={[0.278, 14.77, 5.125]} scale={[0.077, 1, 0.342]} />
      <mesh geometry={nodes.polySurface18_FIVE_0.geometry} material={materials.FIVE} position={[-2.385, 17.99, -1.266]} scale={[11.574, 11.086, 11.086]} />
      <mesh geometry={nodes.polySurface22_FIVE_0.geometry} material={materials.FIVE} position={[-2.41, 18.521, -1.193]} scale={[11.246, 11.822, 11.086]} />
      <mesh geometry={nodes.polySurface24_FIVE_0.geometry} material={materials.FIVE} position={[-2.514, 18.078, -1.27]} scale={11.398} />
      <mesh geometry={nodes.polySurface25_FIVE_0.geometry} material={materials.FIVE} position={[-2.514, 18.078, -1.307]} scale={11.398} />
      <mesh geometry={nodes.polySurface49_FIVE_0.geometry} material={materials.FIVE} position={[-0.874, 12.452, 5.746]} rotation={[0, Math.PI / 4, 0]} scale={0.451} />
      <mesh geometry={nodes.polySurface118_FIVE_0.geometry} material={materials.FIVE} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface119_FIVE_0.geometry} material={materials.FIVE} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface69_FIVE_0.geometry} material={materials.FIVE} position={[-4.581, 17.359, -3.991]} scale={[2.546, 1.877, 2.546]} />
      <mesh geometry={nodes.polySurface71_FIVE_0.geometry} material={materials.FIVE} position={[-4.563, 17.376, -3.973]} scale={[2.531, 1.866, 2.531]} />
      <mesh geometry={nodes.polySurface78_FIVE_0.geometry} material={materials.FIVE} position={[-7.268, 1.756, -8.311]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.polySurface79_FIVE_0.geometry} material={materials.FIVE} position={[-7.268, 1.756, -8.311]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.polySurface80_FIVE_0.geometry} material={materials.FIVE} position={[-5.711, 2.754, 4.975]} scale={[2.255, 1.996, 1.397]} />
      <mesh geometry={nodes.polySurface82_FIVE_0.geometry} material={materials.FIVE} position={[-5.711, 2.754, 4.975]} scale={[2.255, 1.996, 1.397]} />
      <mesh geometry={nodes.polySurface98_FIVE_0.geometry} material={materials.FIVE} position={[-3.469, 5.488, 4.101]} scale={[1.025, 1.074, 0.285]} />
      <mesh geometry={nodes.pPlane1_FIVE_0.geometry} material={materials.FIVE} position={[-0.413, 17.333, 0.74]} scale={1.69} />
      <mesh geometry={nodes.pPlane6_FIVE_0.geometry} material={materials.FIVE} position={[1.932, 13.659, 3.147]} rotation={[0, -Math.PI / 4, -Math.PI / 2]} scale={0.308} />
      <mesh geometry={nodes.pPlane7_FIVE_0.geometry} material={materials.FIVE} position={[1.944, 6.011, 3.143]} rotation={[-Math.PI / 2, 0, -2.356]} scale={[1.378, 1, 0.502]} />
      <mesh geometry={nodes.pCube37_FOUR_0.geometry} material={materials.FOUR} position={[4.146, 2.714, -0.8]} scale={[0.086, 1.214, 1.214]} />
      <mesh geometry={nodes.pCube38_FOUR_0.geometry} material={materials.FOUR} position={[0.464, 13.284, 5.862]} scale={[0.07, 1.214, 1.214]} />
      <mesh geometry={nodes.pCube5_FOUR_0.geometry} material={materials.FOUR} position={[-0.315, 16.701, 0.855]} scale={[2.091, 0.513, 2.091]} />
      <mesh geometry={nodes.pCube58_FOUR_0.geometry} material={materials.FOUR} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.pCube59_FOUR_0.geometry} material={materials.FOUR} position={[-5.613, 12.326, 6.969]} scale={[1, 1, 0.956]} />
      <mesh geometry={nodes.pCube6_FOUR_0.geometry} material={materials.FOUR} position={[-0.315, 17.367, 0.855]} scale={[2.091, 0.513, 2.091]} />
      <mesh geometry={nodes.pCube87_FOUR_0.geometry} material={materials.FOUR} position={[3.141, 12.228, -3.255]} scale={[0.015, 0.124, 1.011]} />
      <mesh geometry={nodes.pCube88_FOUR_0.geometry} material={materials.FOUR} position={[3.141, 11.209, -4.271]} rotation={[Math.PI / 2, 0, 0]} scale={[0.015, 0.124, 1.011]} />
      <mesh geometry={nodes.pCylinder25_FOUR_0.geometry} material={materials.FOUR} position={[-6.094, 4.229, 4.62]} scale={[0.326, 0.477, 0.326]} />
      <mesh geometry={nodes.pCylinder26_FOUR_0.geometry} material={materials.FOUR} position={[-5.372, 4.229, 4.62]} rotation={[0, 0.837, 0]} scale={[0.326, 0.477, 0.326]} />
      <mesh geometry={nodes.pCylinder36_FOUR_0.geometry} material={materials.FOUR} position={[3.154, 12.677, 0.198]} rotation={[0, 0, -Math.PI / 2]} scale={[0.427, 0.073, 0.427]} />
      <mesh geometry={nodes.pCylinder37_FOUR_0.geometry} material={materials.FOUR} position={[3.154, 12.677, -1.131]} rotation={[0, 0, -Math.PI / 2]} scale={[0.427, 0.073, 0.427]} />
      <mesh geometry={nodes.polySurface101_FOUR_0.geometry} material={materials.FOUR} position={[-4.27, 1.756, 2.59]} />
      <mesh geometry={nodes.polySurface102_FOUR_0.geometry} material={materials.FOUR} position={[-4.27, 1.756, 2.59]} />
      <mesh geometry={nodes.polySurface104_FOUR_0.geometry} material={materials.FOUR} position={[-4.087, 1.756, 2.416]} />
      <mesh geometry={nodes.polySurface105_FOUR_0.geometry} material={materials.FOUR} position={[-4.087, 1.756, 2.416]} />
      <mesh geometry={nodes.polySurface106_FOUR_0.geometry} material={materials.FOUR} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface108_FOUR_0.geometry} material={materials.FOUR} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface110_FOUR_0.geometry} material={materials.FOUR} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface111_FOUR_0.geometry} material={materials.FOUR} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface13_FOUR_0.geometry} material={materials.FOUR} position={[-1.907, 1.361, 0.353]} />
      <mesh geometry={nodes.polySurface20_FOUR_0.geometry} material={materials.FOUR} position={[-5.711, 2.754, 4.975]} scale={[2.255, 1.996, 1.397]} />
      <mesh geometry={nodes.polySurface31_FOUR_0.geometry} material={materials.FOUR} position={[-1.608, 4.325, 0.221]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.713, 1]} />
      <mesh geometry={nodes.polySurface32_FOUR_0.geometry} material={materials.FOUR} position={[-1.169, 4.236, 2.732]} rotation={[Math.PI, 0, 0]} scale={[0.908, 0.452, 0.908]} />
      <mesh geometry={nodes.polySurface51_FOUR_0.geometry} material={materials.FOUR} position={[-4.385, 12.308, 5.399]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.713, 1]} />
      <mesh geometry={nodes.polySurface52_FOUR_0.geometry} material={materials.FOUR} position={[-4.385, 12.07, 5.399]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.713, 1]} />
      <mesh geometry={nodes.polySurface53_FOUR_0.geometry} material={materials.FOUR} position={[-1.268, 12.984, 0.283]} scale={[0.881, 0.713, 0.881]} />
      <mesh geometry={nodes.polySurface54_FOUR_0.geometry} material={materials.FOUR} position={[-1.377, 12.984, 0.406]} scale={[0.881, 0.713, 0.881]} />
      <mesh geometry={nodes.polySurface55_FOUR_0.geometry} material={materials.FOUR} position={[-0.369, 4.593, -0.552]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 0.713, 1]} />
      <mesh geometry={nodes.polySurface56_FOUR_0.geometry} material={materials.FOUR} position={[-0.369, 4.343, -0.552]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 0.713, 1]} />
      <mesh geometry={nodes.polySurface57_FOUR_0.geometry} material={materials.FOUR} position={[0.942, 3.054, -0.713]} rotation={[0, -1.455, 0]} scale={[1, 0.713, 1]} />
      <mesh geometry={nodes.polySurface58_FOUR_0.geometry} material={materials.FOUR} position={[-3.969, 4.593, -0.552]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 0.713, 1]} />
      <mesh geometry={nodes.polySurface59_FOUR_0.geometry} material={materials.FOUR} position={[-3.969, 4.343, -0.552]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 0.713, 1]} />
      <mesh geometry={nodes.polySurface60_FOUR_0.geometry} material={materials.FOUR} position={[-3.264, 18.209, -7.962]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1.44, 1]} />
      <mesh geometry={nodes.polySurface61_FOUR_0.geometry} material={materials.FOUR} position={[-3.223, 18.209, -8.161]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1.44, 1]} />
      <mesh geometry={nodes.polySurface62_FOUR_0.geometry} material={materials.FOUR} position={[0.97, 12.97, -11.256]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1.44, 1]} />
      <mesh geometry={nodes.polySurface63_FOUR_0.geometry} material={materials.FOUR} position={[0.97, 12.756, -11.256]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1.44, 1]} />
      <mesh geometry={nodes.polySurface70_FOUR_0.geometry} material={materials.FOUR} position={[-4.563, 17.364, -3.973]} scale={[2.494, 1.839, 2.494]} />
      <mesh geometry={nodes.polySurface73_FOUR_0.geometry} material={materials.FOUR} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface74_FOUR_0.geometry} material={materials.FOUR} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface75_FOUR_0.geometry} material={materials.FOUR} position={[-7.264, 1.756, -9.017]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.polySurface76_FOUR_0.geometry} material={materials.FOUR} position={[-7.226, 1.756, -8.249]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.polySurface81_FOUR_0.geometry} material={materials.FOUR} position={[-5.711, 2.754, 4.975]} scale={[2.255, 1.996, 1.397]} />
      <mesh geometry={nodes.polySurface83_FOUR_0.geometry} material={materials.FOUR} position={[1.982, 10.841, -10.389]} rotation={[0, -1.571, 0]} scale={[0.822, 1.44, 0.822]} />
      <mesh geometry={nodes.polySurface84_FOUR_0.geometry} material={materials.FOUR} position={[1.794, 10.841, -10.389]} rotation={[0, -1.571, 0]} scale={[0.822, 1.44, 0.822]} />
      <mesh geometry={nodes.polySurface97_FOUR_0.geometry} material={materials.FOUR} position={[-4.907, 8.549, 4.158]} rotation={[-Math.PI / 2, Math.PI / 3, 0]} scale={[1.056, 0.859, 1.056]} />
      <mesh geometry={nodes.pCube7_ONE_0.geometry} material={materials.material} position={[3.621, 2.256, -0.85]} scale={[1, 1, 2.142]} />
      <mesh geometry={nodes.pCube86_ONE_0.geometry} material={materials.material} position={[0, 1.756, 0]} />
      <mesh geometry={nodes.pCylinder17_ONE_0.geometry} material={materials.material} position={[0.661, 9.487, 7.051]} rotation={[0, 0, -Math.PI / 2]} scale={0.187} />
      <mesh geometry={nodes.polySurface5_ONE_0.geometry} material={materials.material} position={[-2.422, 7.299, -1.266]} scale={11.086} />
      <mesh geometry={nodes.polySurface9_ONE_0.geometry} material={materials.material} position={[-9.747, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface99_ONE_0.geometry} material={materials.material} position={[-3.437, 5.519, 3.99]} scale={[1, 1, 0.285]} />
      <mesh geometry={nodes.pCylinder10_SIX_0.geometry} material={materials.material_5} position={[-0.165, 3.117, 4.277]} scale={0.068} />
      <mesh geometry={nodes.pCylinder13_SIX_0.geometry} material={materials.material_5} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.pCylinder20_SIX_0.geometry} material={materials.material_5} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.pCylinder24_SIX_0.geometry} material={materials.material_5} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.pCylinder35_SIX_0.geometry} material={materials.material_5} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface36_SIX_0.geometry} material={materials.material_5} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.pPlane5_SIX_0.geometry} material={materials.material_5} position={[3.178, 2.649, 0.883]} rotation={[0, 0, -Math.PI / 2]} scale={[0.096, 1, 1.134]} />
      <group position={[-40.159, 0, 0]}>
        <mesh geometry={nodes.pasted__LISTS1_group9_pPlane2_THREE_0.geometry} material={materials.THREE} position={[42.54, 2.276, 0.321]} rotation={[0, -Math.PI / 4, 0]} scale={0.456} />
        <mesh geometry={nodes.pasted__LISTS1_group9_pPlane3_THREE_0.geometry} material={materials.THREE} position={[38.935, 9.462, 3.412]} scale={0.456} />
        <mesh geometry={nodes.pasted__pCube228_THREE_0.geometry} material={materials.THREE} position={[42.702, -3.312, 7.278]} scale={0.587} />
        <mesh geometry={nodes.pasted__pCube229_THREE_0.geometry} material={materials.THREE} position={[43.138, -3.202, 4.158]} rotation={[2.585, -0.33, 1.372]} scale={0.587} />
        <mesh geometry={nodes.pasted__pCube230_THREE_0.geometry} material={materials.THREE} position={[43.266, -4.362, 7.597]} scale={0.708} />
        <mesh geometry={nodes.pasted__pCube237_THREE_0.geometry} material={materials.THREE} position={[35.194, -0.263, 1.068]} rotation={[-Math.PI, 0.919, -Math.PI]} scale={0.457} />
        <mesh geometry={nodes.pasted__pCube238_THREE_0.geometry} material={materials.THREE} position={[49.835, -4.35, 0.47]} scale={0.708} />
        <mesh geometry={nodes.pasted__pCube239_THREE_0.geometry} material={materials.THREE} position={[45.661, -3.198, -6.803]} rotation={[1.725, -1.04, 0.179]} scale={0.587} />
        <mesh geometry={nodes.pasted__pCube240_THREE_0.geometry} material={materials.THREE} position={[49.271, -3.301, 0.152]} scale={0.587} />
        <mesh geometry={nodes.pasted__pCube241_THREE_0.geometry} material={materials.THREE} position={[49.531, 4.384, 8.675]} scale={0.708} />
        <mesh geometry={nodes.pasted__pCube242_THREE_0.geometry} material={materials.THREE} position={[46.717, 5.433, 9.004]} scale={0.587} />
        <mesh geometry={nodes.pasted__pCube243_THREE_0.geometry} material={materials.THREE} position={[46.775, 5.54, 5.332]} rotation={[2.585, -0.33, 1.372]} scale={0.587} />
        <mesh geometry={nodes.pasted__pCube244_THREE_0.geometry} material={materials.THREE} position={[40.245, 6.555, 2.96]} rotation={[-Math.PI, 0.919, -Math.PI]} scale={0.457} />
        <mesh geometry={nodes.polySurface125_THREE_0.geometry} material={materials.THREE} position={[41.213, 3.984, 0]} rotation={[0, 0, 0.651]} />
        <mesh geometry={nodes.polySurface127_THREE_0.geometry} material={materials.THREE} position={[41.305, 2.396, 0]} />
        <mesh geometry={nodes.polySurface129_THREE_0.geometry} material={materials.THREE} position={[40.159, 1.756, 0]} />
        <mesh geometry={nodes.polySurface131_THREE_0.geometry} material={materials.THREE} position={[40.159, 1.756, 0]} />
        <mesh geometry={nodes.polySurface132_THREE_0.geometry} material={materials.THREE} position={[41.023, 1.179, 0]} rotation={[0, 0, -0.313]} />
        <mesh geometry={nodes.polySurface135_THREE_0.geometry} material={materials.THREE} position={[35.114, 1.208, 0]} rotation={[0, 0, -0.862]} />
        <mesh geometry={nodes.polySurface136_THREE_0.geometry} material={materials.THREE} position={[39.198, 1.376, -1.466]} rotation={[-0.139, Math.PI / 2, 0]} />
        <mesh geometry={nodes.polySurface137_THREE_0.geometry} material={materials.THREE} position={[39.198, 2.617, -4.382]} rotation={[0.338, Math.PI / 2, 0]} />
        <mesh geometry={nodes.polySurface138_THREE_0.geometry} material={materials.THREE} position={[36.523, 7.047, 4.51]} rotation={[-0.408, Math.PI / 2, 0]} />
        <mesh geometry={nodes.polySurface139_THREE_0.geometry} material={materials.THREE} position={[36.518, 9.115, 3.693]} rotation={[0, 1.571, 0]} />
      </group>
      <mesh geometry={nodes.pCube39_THREE_0.geometry} material={materials.THREE} position={[2.401, 5.018, 2.665]} rotation={[0, -Math.PI / 4, 0]} scale={[0.086, 2.26, 2.26]} />
      <mesh geometry={nodes.polySurface16_THREE_0.geometry} material={materials.THREE} position={[-2.571, 8.822, -1.173]} scale={11.086} />
      <mesh geometry={nodes.polySurface91_THREE_0.geometry} material={materials.THREE} position={[-2.502, 10.075, -1.357]} scale={11.086} />
      <mesh geometry={nodes.polySurface92_THREE_0.geometry} material={materials.THREE} position={[-2.715, 10.183, -1.092]} scale={11.086} />
      <mesh geometry={nodes.polySurface96_THREE_0.geometry} material={materials.THREE} position={[-1.907, 1.756, 0.353]} />
      <group position={[1.032, 10.696, 5.393]} rotation={[0, Math.PI / 4, 0]} scale={0.451}>
        <mesh geometry={nodes.polySurface42_THREE_0.geometry} material={materials.THREE} position={[3.292, -19.811, -12.504]} rotation={[0, -Math.PI / 4, 0]} scale={2.216} />
        <mesh geometry={nodes.polySurface50_THREE_0.geometry} material={materials.THREE} position={[-3.541, 3.892, -2.435]} />
      </group>
      <mesh geometry={nodes.pCylinder21_THREE_0.geometry} material={materials.THREE} position={[1.85, 13.659, 3.066]} rotation={[0, -Math.PI / 4, -Math.PI / 2]} scale={0.137} />
      <mesh geometry={nodes.polySurface85_THREE_0.geometry} material={materials.THREE} position={[-2.437, 17.99, -1.363]} scale={11.086} />
      <mesh geometry={nodes.polySurface86_THREE_0.geometry} material={materials.THREE} position={[-2.467, 17.99, -1.393]} scale={11.086} />
      <mesh geometry={nodes.polySurface87_THREE_0.geometry} material={materials.THREE} position={[-2.674, 18.098, -1.133]} scale={11.086} />
      <mesh geometry={nodes.polySurface89_THREE_0.geometry} material={materials.THREE} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.pCube34_THREE_0.geometry} material={materials.THREE} position={[0.766, 10.5, 5.763]} rotation={[0, -Math.PI / 2, 0]} scale={0.645} />
      <mesh geometry={nodes.pCube35_THREE_0.geometry} material={materials.THREE} position={[-0.14, 2.848, 4.404]} rotation={[Math.PI, 0, Math.PI]} scale={0.496} />
      <mesh geometry={nodes.pCube36_THREE_0.geometry} material={materials.THREE} position={[0.587, 11.194, -6.577]} scale={0.581} />
      <mesh geometry={nodes.pCylinder40_THREE_0.geometry} material={materials.THREE} position={[-6.633, 13.916, 7.051]} scale={0.143} />
      <mesh geometry={nodes.pCylinder41_THREE_0.geometry} material={materials.THREE} position={[3.121, 7.126, 1.209]} rotation={[0, 1.571, 0]} scale={0.143} />
      <mesh geometry={nodes.polySurface120_THREE_0.geometry} material={materials.THREE} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface121_THREE_0.geometry} material={materials.THREE} position={[-3.577, 1.756, -10.407]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.polySurface122_THREE_0.geometry} material={materials.THREE} position={[0.482, 14.396, 5.125]} scale={[0.077, 1, 0.342]} />
      <mesh geometry={nodes.pCube10_THREE_0.geometry} material={materials.THREE} position={[-6.633, 11.854, 8.145]} rotation={[0, -1.571, 0]} scale={[1.673, 4.625, 0.275]} />
      <mesh geometry={nodes.pCube11_THREE_0.geometry} material={materials.THREE} position={[-6.633, 7.117, 8.145]} rotation={[0, -1.571, 0]} scale={[1.673, 4.625, 0.275]} />
      <mesh geometry={nodes.pCube9_THREE_0.geometry} material={materials.THREE} position={[4.12, 5.749, 1.209]} scale={[1.25, 3.454, 0.275]} />
      <mesh geometry={nodes.pCylinder27_THREE_0.geometry} material={materials.THREE} position={[-6.633, 8.937, 7.241]} rotation={[Math.PI / 2, 0, 0]} scale={[0.034, 0.093, 0.034]} />
      <mesh geometry={nodes.pCylinder28_THREE_0.geometry} material={materials.THREE} position={[-6.633, 9.282, 7.241]} rotation={[Math.PI / 2, 0, 0]} scale={[0.034, 0.093, 0.034]} />
      <mesh geometry={nodes.pCylinder29_THREE_0.geometry} material={materials.THREE} position={[-6.633, 9.806, 7.241]} rotation={[Math.PI / 2, 0, 0]} scale={[0.034, 0.093, 0.034]} />
      <mesh geometry={nodes.pCylinder30_THREE_0.geometry} material={materials.THREE} position={[-6.633, 11.842, 7.241]} rotation={[Math.PI / 2, 0, 0]} scale={[0.034, 0.093, 0.034]} />
      <mesh geometry={nodes.pCylinder31_THREE_0.geometry} material={materials.THREE} position={[-6.633, 13.878, 7.241]} rotation={[Math.PI / 2, 0, 0]} scale={[0.034, 0.093, 0.034]} />
      <mesh geometry={nodes.pCylinder32_THREE_0.geometry} material={materials.THREE} position={[3.409, 7.126, 1.209]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.034, 0.093, 0.034]} />
      <mesh geometry={nodes.pCylinder33_THREE_0.geometry} material={materials.THREE} position={[3.409, 5.71, 1.209]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.034, 0.093, 0.034]} />
      <mesh geometry={nodes.pCylinder34_THREE_0.geometry} material={materials.THREE} position={[3.409, 4.384, 1.209]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.034, 0.093, 0.034]} />
      <mesh geometry={nodes.pCylinder38_THREE_0.geometry} material={materials.THREE} position={[-3.741, 2.555, 5.165]} rotation={[0, 1.148, 0]} scale={[0.624, 0.799, 0.624]} />
      <mesh geometry={nodes.pCylinder39_THREE_0.geometry} material={materials.THREE} position={[-3.741, 4.059, 5.165]} rotation={[0, 1.148, 0]} scale={[0.532, 0.681, 0.532]} />
      <mesh geometry={nodes.pPlane8_THREE_0.geometry} material={materials.THREE} position={[-3.741, 3.626, 5.165]} rotation={[0, 1.148, 0]} scale={0.716} />
      <mesh geometry={nodes.pCube76_TWO_0.geometry} material={materials.material_1} position={[-1.907, 1.756, 0.353]} />
      <mesh geometry={nodes.polySurface23_TWO_0.geometry} material={materials.material_1} position={[-2.422, 17.99, -1.266]} scale={11.086} />
      <mesh geometry={nodes.polySurface26_TWO_0.geometry} material={materials.material_1} position={[-4.512, 17.99, -1.266]} scale={[0.302, 11.086, 11.086]} />
      <mesh geometry={nodes.polySurface27_TWO_0.geometry} material={materials.material_1} position={[-2.068, 17.99, -1.266]} scale={[0.302, 11.086, 11.086]} />
    </group>
  )
}

useGLTF.preload('models/scene.glb')
